[package]
name = "slog-stdlog"
version = "2.0.0-3.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Standard Rust log crate adapter to slog-rs"
keywords = ["slog", "logging", "json", "log"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-stdlog"
homepage = "https://github.com/slog-rs/stdlog"
repository = "https://github.com/slog-rs/stdlog"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "~2.0.0-3"
slog-scope = "~2.0.0-3"
slog-term = "~2.0.0-3"
log = "0.3.6"
crossbeam = "0.2.9"
